version: '3.7'

services: 
  api:
    build: ./backend
    image: mishaelr/api:1
    container_name: backendcontainer
    ports:
      - '5000:5000'
    networks:
      - mynetwork
    depends_on:
      - mongo
  client:
    build: ./client
    image: mishaelr/frontend:1
    container_name: clientcontainer
    ports:
      - '3000:3000'
    networks:
      - mynetwork 
    depends_on:
      - api

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mish
      MONGO_INITDB_ROOT_PASSWORD: mish 
    networks:
      - mynetwork 
    volumes:
      - mydb:/data/db  

networks:
  mynetwork:
    driver: bridge
volumes:
  mydb: 

   
 
