apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-front
  namespace: my-yolo-app
  labels:
    app: yolo
    component: front
spec:
  replicas: 3
  selector:
    matchLabels:
      component: front
  template:
    metadata:
      labels:
        app: yolo
        component: front
    spec:
      containers:
        - name: clientcontainer
          image: mishaelr/frontend:1
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: yolo-pv
            mountPath: /var/www/html
      volumes:
      - name: yolo-pv
        persistentVolumeClaim:
          claimName: yolo-pvc   
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-front
  namespace: my-yolo-app
  labels:
    app: yolo
    component: front
spec:
  type: LoadBalancer
  selector:
    app: yolo
    component: front
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http

